In [7]:
import numpy as np
import pandas as pd
import matplotlib as plt
import polars as pl

In [10]:
book_data = pd.read_csv('amazon_reviews_us_Books_v1_02.tsv', sep='\t',on_bad_lines='warn')

/var/folders/qg/cs1vp31s60j1j1c4k31w9tdw0000gn/T/ipykernel_14701/2027929391.py:1: ParserWarning: Skipping line 1680001: expected 15 fields, saw 22

  book_data = pd.read_csv('amazon_reviews_us_Books_v1_02.tsv', sep='\t',on_bad_lines='warn')

In [20]:
book_data[book_data['customer_id'] == 53096589]

,marketplace,customer_id,review_id,product_id,product_parent,product_title,product_category,star_rating,helpful_votes,total_votes,vine,verified_purchase,review_headline,review_body,review_date
1614568,US,53096589,R2JYT0MI478PY3,0374523894,215877982,Seeing Things,Books,5.0,2.0,3.0,N,N,In Honor Of St Patrick's Day...,i thought i'd read a irish writer. i couldn't ...,2002-03-18
1615623,US,53096589,RVO5XJHT4O03T,0679721746,462852429,The Commitments,Books,4.0,0.0,0.0,N,N,my other irish book...,this one succeeds largely due to its &quot; ca...,2002-03-18
1615628,US,53096589,RJOZVVEQWZRZ3,0679766626,574131654,Last Orders,Books,5.0,3.0,4.0,N,N,Modern day working class tales....,"seminal tale of four men: lenny, ray, vic and ...",2002-03-18
1615887,US,53096589,R2R8OZTR23Z8DU,0393320189,898276764,Vice: New and Selected Poems,Books,5.0,1.0,2.0,N,N,no vice in owning this book...,"one of the strongest, most dynamic poetic voic...",2002-03-18
1630010,US,53096589,R3S50TSJN7OGND,0452266777,826207107,"Lucy (Contemporary Fiction, Plume)",Books,5.0,2.0,3.0,N,N,Lucy's Got Issues...,she is the type of woman you want to hate one ...,2002-03-06
1642584,US,53096589,R6MAVX9REYOR,0252062876,294160429,The Bingo Long Traveling All-Stars and Motor K...,Books,5.0,5.0,7.0,N,N,The Soul Of Baseball...,there was never a dull moment reading this. in...,2002-02-24
1642968,US,53096589,R2GXJB8WF44Q2U,0679760008,645758434,Shadow and Act,Books,5.0,26.0,29.0,N,N,memoirs from a unique brotha,not merely a statement on being a black man in...,2002-02-24
1651259,US,53096589,R25OAEATSNICJJ,086316109X,199202211,No Noose Is Good Noose,Books,2.0,0.0,0.0,N,N,The Angry Young Man,"when i first started reading poetry, stuff lik...",2002-02-17
1660154,US,53096589,R2LQH18EWGN3GU,0446527998,734163607,Church Folk,Books,4.0,2.0,3.0,N,N,Can I Get A Witness ?,i met michelle in d.c. last summer at sistersp...,2002-02-10
1671255,US,53096589,RAPDFGKU4M4D,0889104689,937861332,In the House of Slaves,Books,4.0,4.0,4.0,N,N,in defense of evelyn's poetry...,"i love the way she writes about dark subjects,...",2002-02-01

In [21]:
survey_data = pd.read_csv("survey.csv")

In [22]:
survey_data

,Duration (in seconds),RecordedDate,ResponseId,Q-prolific-mturk,q-demos-age,Q-demos-hispanic,Q-demos-race,Q-demos-education,Q-demos-income,Q-demos-gender,...,Q-data-value-any_1_TEXT,Q-sell-YOUR-data,Q-sell-consumer-data,Q-small-biz-use,Q-census-use,Q-research-society,Q-attn-check,showdata,incentive,connect
0,332,9/21/2022 10:00:17,R_1ou69fj4DQGsVcp,NaN,35 - 44 years,No,Black or African American,High school diploma or GED,"$25,000 - $49,999",Female,...,NaN,No,No,No,No,No,"Yes,No,I don't know",False,bonus-50,NaN
1,488,9/21/2022 10:02:24,R_24dboHVOzohx1kw,NaN,25 - 34 years,No,White or Caucasian,Bachelor's degree,"$25,000 - $49,999",Male,...,NaN,Yes if I get part of the profit,Yes,No,Yes,Yes,"Yes,No,I don't know",False,bonus-05,NaN
2,309,9/21/2022 10:10:47,R_2UbJL30HRjK1sdD,NaN,45 - 54 years,No,White or Caucasian,High school diploma or GED,"$100,000 - $149,999",Male,...,NaN,No,No,No,No,Yes,"Yes,No,I don't know",False,bonus-05,NaN
3,339,9/21/2022 10:13:03,R_UPXamGKtmf4RVIZ,NaN,25 - 34 years,No,White or Caucasian,High school diploma or GED,"$25,000 - $49,999",Male,...,NaN,No,No,No,No,Yes,"Yes,No,I don't know",False,bonus-50,NaN
4,674,9/21/2022 11:36:51,R_2dYk5auG9Fv5Qve,NaN,35 - 44 years,Yes,White or Caucasian,"Graduate or professional degree (MA, MS, MBA, ...","$50,000 - $74,999",Male,...,NaN,No,No,No,No,No,"Yes,No,I don't know",True,control,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6320,818,3/21/2023 21:59:02,R_2uKaOXO8LfgoFf3,Yes,35 - 44 years,No,Black or African American,High school diploma or GED,"Less than $25,000",Male,...,NaN,No,No,I don't know,No,No,"Yes,No,I don't know",True,bonus-50,True
6321,172,3/21/2023 22:15:05,R_3lEpFGLEmx2Sv2J,Yes,35 - 44 years,No,White or Caucasian,High school diploma or GED,"$50,000 - $74,999",Female,...,5,No,No,No,No,Yes,"Yes,No,I don't know",False,bonus-20,True
6322,579,3/21/2023 22:17:43,R_27Ee9Bw4FyMOZuZ,No,45 - 54 years,No,Other,Prefer not to say,"Less than $25,000",Female,...,NaN,No,No,No,No,No,"Yes,No,I don't know",True,control,True
6323,1244,3/21/2023 22:29:56,R_2ZZSS68rfn9BMtt,Yes,45 - 54 years,No,White or Caucasian,Bachelor's degree,"Less than $25,000",Male,...,NaN,Yes if I get part of the profit,Yes if consumers get part of the profit,Yes,Yes,Yes,"Yes,No,I don't know",False,bonus-50,True
6324,674,3/21/2023 23:03:09,R_273TMGuLM3jXisi,No,25 - 34 years,No,White or Caucasian,High school diploma or GED,"$25,000 - $49,999",Male,...,NaN,No,No,Yes,No,Yes,"Yes,No,I don't know",True,altruism,True